#Create Custom Container Image
#Push to DockerHub Registry
---
- hosts: localhost
  tasks:
  - name: Pull .war artifact from Artifactory
    become: true
    get_url:
      url: http://localhost:8082/artifactory/libs-release/com/iwayq/iwayQApp/1.0-RELEASE/iwayQApp-1.0-RELEASE.war
      dest: ./
      url_username: admin
      url_password: RQb7ctKtx5KFP6q

  - name: Rename .war Artifact
    command: mv iwayQApp-1.0-RELEASE.war iwayq.war

  - name: Pull Tomcat Container Image
    docker_image:
      name: tomcat:latest
      source: pull

  - name: Build image and with build args
    docker_image:
      name: iwayq
      build:
        path: ./
        pull: no
        args:
          listen_port: 8080
      source: build

  - name: Log into DockerHub
    docker_login:
     username: bindian0509
     password: oracle@123


  - name: Push to docker hub
    docker_image:
      name: iwayq
      repository: bindian0509/iwayq:1.0
      push: yes
      source: local
